export const ar = {
  //weekDays
  sun: "الأحد",
  mon: "الإثنين",
  tue: "الثلاثاء",
  wed: "الأربعاء",
  thu: "الخميس",
  fri: "الجمعة",
  sat: "السبت",
  sunday: "Sunday",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  //monthFullNames
  january: 'يناير',
  february: 'فبراير',
  march: 'مارس',
  april: 'أبريل',
  may: 'مايو',
  june: 'يونيو',
  july: 'يوليو',
  august: 'أغسطس',
  september: 'سبتمبر',
  october: 'أكتوبر',
  november: 'نوفمبر',
  december: 'ديسمبر',
  Jan: 'يناير',
  Feb: 'فبراير',
  Mar: 'مارس',
  Apr: 'أبريل',
  May: 'مايو',
  Jun: 'يونيو',
  Jul: 'يوليو',
  Aug: 'أغسطس',
  Sep: 'سبتمبر',
  Oct: 'أكتوبر',
  Nov: 'نوفمبر',
  Dec: 'ديسمبر',
  pleaseSelect: 'الرجاء التحديد',

  //Package Home 
  packages: 'البرامج',
  alreadyRegistered: 'لقد قمت بالتسجيل في أحد البرامج، إذا كنت ترغب في تسجيل جديد يُرجى زيارة فُرع النادي الرياضي لإكمال عملية تسجيل البصمة!',

  //Package Details
  oneMonth: 'شهر واحد',
  twoMonth: 'شهرين',
  threeMonth: 'ثلاث أشهر',
  yes: 'نعم',
  no: 'لا',
  packageDetails: 'تفاصيل البرنامج',
  description: 'الوصف',
  doYouWantTrainer: 'هل تريد مُدرب؟',
  period: 'الفترة',
  next: 'التالي',
  pleaseSelectTrainer: 'يرجى إختيار المُدرب و الفترة',
  pleaseSelectRequiredField: 'يرجى إختيار الحقل المطلوب',
  yourCurrentPlanSubscriptionIsActiveThrough: 'إشتراكك صالح لغاية',
  youCantBuyTheSamePackageTwice: 'لا يمكنك شراء نفس الباقة مرتين!',

  //Trainer Question One
  beginner: 'مبتدئ',
  intermidiate: 'متوسط',
  advanced: 'متقدم',
  whatIsYourLevel: `ما هو مستواك؟`,
  selectYourFitnessLevel: 'حدد مستوى لياقتك',
  pleaseSelectOneOption: 'يرجى تحديد خيار واحد',

  //Trainer Question Two
  oneDayAWeek: 'يوم في الأسبوع',
  twoDayAWeek: 'يومين في الإسبوع',
  threeDayAWeek: 'ثلاثة أيام في الإسبوع',
  fourDayAWeek: 'أربعة أيام في الإسبوع',
  fiveDayAWeek: 'خمسة أيام في الإسبوع',
  sixDayAWeek: 'ستة أيام في الإسبوع',
  sevenDayAWeek: 'سبعة أيام في الإسبوع',
  howManyDays: `كم يوماً تخطط لممارسة الرياضة في الأسبوع؟`,

  //Trainer Question Three
  lossWeight: 'إنقاص الوزن',
  gainWeight: 'زيادة الوزن',
  whatIsYourGoal: 'ما هو هدفك؟',

  //Payment Question
  payOnline: 'الدفع عبر الإنترنت',
  payAtGym: 'الدفع في النادي الرياضي',
  submit: 'موافق',
  makePayment: 'يرجى الدفع',
  paymentMethod: 'طريقة الدفع',
  totalAmount: 'المبلغ الإجمالي',
  trainerFees: 'رسوم المدربين',
  VAT: 'الضريبة',
  congratulations: 'تهانينا !!',
  successfullyRequest: 'لقد تم تسجيل طلبك بنجاح',
  successfullyRequestFingerPrint: 'لقد تم تسجيل طلبك بنجاح، يرجى زيارة النادي الرياضي لإستكمال عملية التسجيل.',

  //Renew packages
  currentPackages: 'البرامج الحالية',
  active: 'فعال',
  newPackages: 'برامج جديدة',
  renew: 'تجديد',
  alert: 'تحذير',
  currentPlan: 'الرزمة الحالية',
  previousPlan: 'الحزمة السابقة',
  inActive: 'غير نشط',
  yourPreviousPlanSubscriptionWasActiveThrough: 'اشتراكك في الباقة السابقة كان نشطًا حتى ',
  //HomePage 
  myWorkouts: 'تماريني',
  mySchedule: 'جدول مواعيدي',
  myTrainers: 'المُدربين',
  gymShop: 'سوق النادي',
  myDietPlan: 'خطة النظام الغذائي',
  myPackages: 'برامجي',
  startPackage: 'بدء البرنامج',
  offers: 'العروض',
  days: 'الأيام',
  daysLeft: 'الأيام المتبقية',
  expiryOn: 'ينتهي في',
  expiredOn: 'انتهت يوم',
  firstPay: 'يرجى دفع قيمة البرنامج',
  memberId: 'رقم العضوية',
  mobile: 'رقم النقال',

  //Workouts 
  workouts: 'التمارين',
  workoutsAndCardios: 'التمارين و الكارديو',
  sets: 'جلس',
  reps: `اعادة \ عد`,
  kg: 'كيلوغرام',
  time: 'الوقت',
  km: 'كيلومتر',
  startWorkout: 'بدء التمرين',
  noData: 'عُذراً .. لا تتوفر بيانات!',
  instructions: 'التعليمات',

  //Schedules
  schedule: 'جدول المواعيد',
  classes: 'الحصص التدريبية',


  //Diet
  diets: 'النظام الغذائي',
  dietPlan: 'خطة النظام الغذائي',
  calories: 'السعرات الحرارية',

  //Trainer
  myTrainer: 'المُدربين',
  trainerDetails: 'تفاصيل المُدربين',

  //BMI 
  result: 'النتيجة',
  underWeight: 'وزن ناقص',
  normal: 'طبيعي',
  overWeight: 'وزن زائد',
  obese: 'سُمنة',
  severelyObese: 'السمنة المُفرطة',
  verySeverelyObese: 'شديد السُمنة',
  gender: 'الجنس',
  age: 'العمر',
  calculate: 'إحسب',
  weightProgress: 'مرحلة تطور الوزن',
  start: 'البداية',
  current: 'حالياً',
  goal: 'الهدف',
  today: 'اليوم',
  trackWeight: 'مُتابعة الوزن',
  howMuchDoYouWeightToday: 'كم وزنك اليوم؟',
  whatIsYourGoalWeight: 'ماهو الوزن الذي تطمح للوصول إليه ؟',
  updateWeight: 'تعديل الوزن',

  //Menu items
  webShop: 'السوق الإلكتروني',
  addToCart: 'أضف إلى السلة',
  buyNow: 'الشراء الآن',
  description: 'الوصف',
  yourCartIsEmpty: 'سلة التسوق خالية',
  addItemsToItNow: 'أضف العناصر لسلة التسوق',
  myCart: 'سلة التسوق',
  subTotal: 'المجموع',
  discount: 'التخفيض',
  tax: 'الضريبة',
  total: 'المجموع الإجمالي',
  checkout: 'الدفع',
  payWithCreditCard: 'الدفع عن طريق بطاقة الائتمان',
  myOrders: 'طلباتي',
  order: 'الطلبية',
  dateAndTime: 'التاريخ و الوقت',
  paymentMode: 'طريقة الدفع',
  invoice: 'الفاتورة',
  invoices: 'الفواتير',
  orderDetails: 'تفاصيل الطلب',
  addedToCart: 'أضف إلى السلة',
  QTY: 'الكمية',
  amount: 'المبلغ',
  orderHistory: 'سجل الطلبات',

  //Water Intake 
  pleaseSelectADateToContinue: 'يرجى تحديد تاريخ للمتابعة',
  drunk: 'تم شُرب',
  outOf: 'من',
  target: 'الكمية المطلوبة',
  addWater: 'أضف كمية الماء',
  updateTarget: 'تعديل الكمية المطلوبة',
  dailyTarget: 'الهدف اليومي',
  progress: 'نِسبة الشُرب',
  trackingWaterProgress: 'مُتابعة نِسبة الشُرب',
  reminder: 'التذكير',
  setAReminder: 'ضبط التذكير',
  customize: 'تخصيص كمية الشُرب',
  enterWaterLevel: 'أدخل مستوى الماء',
  records: 'تسجيل',
  enterTarget: 'أدخل كمية الماء المطلوبة',
  setReminderToDrinkWater: 'ضبط التذكير لشرب الماء',
  input: 'يرجى إدخال المعلومات الخاصة بك وتخصيص خُطة الترطيب.',
  from: 'من',
  to: 'إلى',
  remindMeEvery: 'ذكرني كُل',
  remindMe: 'ذكرني',
  save: 'حفظ',
  setYourTimeIntervals: 'ضبط فترات شرب الماء',
  setNumberOfReminders: 'ضبط عدد مرات التذكير',
  of: 'من',
  enterWaterLevel: 'أدخل مستوى الماء',

  //Drawer Menu
  home: 'الصفحة الرئيسية',
  myProfile: 'ملفي الشخصي',
  myClasses: 'الحصص التدريبية',
  qrCode: 'رمز المسح QR ',
  myInvoices: 'فواتيري',
  contact: 'اتصل بنا',
  feedback: 'المُلاحظات والشكاوي',
  aboutUs: 'معلومات عنا',
  exploreTheCentres: 'استكشف المراكز',
  referAFriend: 'أوص أحد الأصدقاء',
  settings: 'الإعدادات',
  logout: 'الخروج',
  qr: 'رمز المسح QR',

  //Bottom Tab Navigator
  reward: 'المكافآت',
  BMI: 'كُتلة الجسم',
  waterIntake: 'كمية المياه',

  //Trainer Waorkout 
  addWorkout: 'إضافة التمارين',
  selectMember: 'إختر عضو',
  cardio: 'كارديو',
  assignWorkouts: 'تعين تمارين',
  activities: 'الأنشطة',
  note: 'ملاحظة',
  workoutLevel: 'مستوى التمارين',
  updateWorkout: 'تعديل التمارين',
  weightTrainer: 'الوزن',
  distance: 'المسافة',
  missingFields: 'بعض الحقول مفقودة',

  //Trainer Diet Plan
  dietPlanSessions: 'ترة النظام الغذائي',
  assignDietPlans: 'تعين برنامج غذائي',
  foodItems: 'المواد الغذائية',
  QTYOrGrams: 'الكمية / غرام',
  specOrAdvice: 'المواصفات / النصائح',
  dietPlans: 'برنامج غذائي',
  add: 'أضف',
  search: 'بحث',

  //settings
  languages: 'اللغة',
  changePassword: 'تغير كلمة المرور',
  notifications: 'إشعارات',

  //Trainer Home 
  empId: 'رقم الموظف',

  //Classes
  branch: 'الفرع',
  remainingSeats: 'الحجوزات المتبقية',
  classDetails: 'تفاصيل الحصة التدريبية',
  daysIncluded: 'الأيام المشمولة',
  bookNow: 'إحجز الآن',
  room: 'الغرفة',

  //Feedbacks
  feedbacks: 'إرسال الملاحظات',
  suggestions: 'الاقتراحات',
  complaints: 'الشكاوي',
  feedbackDetails: 'تفاصيل الملاحظات',
  gymOwnerComments: 'تعليقات الإدارة',
  types: 'اكتب',

  //Contact Us
  contactUs: 'تواصل معنا',
  showRoute: 'خارطة الطريق',
  maps: 'الخريطة',
  estTime: 'الوقت',
  cancel: 'إلغاء',
  sorry: 'عذراً.. لم يتم العثور على المسار من موقعك الحالي إلى صالة الألعاب الرياضية، يرجى المحاولة في مواقع فروعنا الأخرى',

  //Rewards

  rewards: 'المكافئات',
  giftCards: 'بطاقات الهدايا',
  history: 'السجل',
  points: 'النقاط',
  currentPoints: 'النقاط الحالية',
  end: 'إلى',
  redeem: 'إستبدال',
  totalPoints: 'مجموع النقاط',
  giftCardDetails: 'تفاصيل بطاقة الهدية',
  rewardDetails: 'تفاصيل المكافئات',

  //Login and Sign up
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  login: 'تسجيل الدخول',
  forgotPassword: "هل نسيت كلمة المرور؟",
  forgotPasswordSuccess: "تم إرسال بريد إلكتروني بكلمة المرور الخاصة بك على معرف البريد الإلكتروني المسجل الخاص بك !",
  dontHaveAnAccount: "ليس لديك حساب؟",
  signUp: "تسجيل حساب جديد",
  name: 'اسم',
  personalId: 'الرقم الشخصي',
  dateOfBirth: 'تاريخ الميلاد',
  age: 'العمر',
  height: 'الطول (سم)',
  weight: 'الوزن (كجم)',
  emergencyNumber: 'رقم الطواريء',
  relationship: 'صلة القرابة',
  nationality: 'الجنسية',
  gender: 'الجنس',
  branch: 'الفرع',
  uploadPhoto: 'تحميل الصورة',
  takePicture: 'أخذ صورة',
  selectFromGallery: 'الإختيار من ألبوم الصور',
  confirmPassword: 'تأكيد كلمة المرور',
  nameError: 'حقل الإسم فارغ',
  nameErrorTwo: 'يرجى إدخال الإسم',
  emailError: 'حقل البريد الإلكتروني فارغ',
  emailErrorTwo: 'صيغة البريد الإلكتروني غير صحيحة',
  emailErrorThree: 'يرجى كتابة البريد الإلكتروني',
  personalError: 'حقل الرقم الشخصي فارغ',
  personalErrorTwo: 'يرجى كتابة الرقم الشخصي',
  mobileError: 'حقل رقم النقال فارغ',
  mobileErrorTwo: 'يرجى كتابة رقم صحيح',
  mobileErrorThree: 'يرجى كتابة رقم الإتصال',
  dobError: 'حقل تاريخ ميلاد فارغ',
  dobErrorTwo: 'حسب عمرك، لايمكنك الإشتراك',
  nationalityError: 'حقل الجنسية فارغ',
  genderError: 'حقل الجنس فارغ',
  branchError: 'حقل الفرع فارغ',
  imageError: 'يرجى إدخال الصورة',
  passwordError: 'حقل كلمة المرور فارغ',
  confirmError: 'حقل تأكيد كلمة المرور فارغ',
  passwordErrorTwo: 'يجب أن تكون كلمة المرور من 5 حروف و أرقام كحد أدنى',
  confirmErrorTwo: 'حقل تأكيد كلمة المرور فارغ',
  confirmErrorThree: 'كلمة المرور غير متطابقة',
  emailVerification: 'التحقق من البريد الإلكتروني',
  verification: 'تم إرسال رمز التحقق على بريدك الإلكتروني ، يرجى التحقق من حسابك عن طريق إدخال رمز التحقق!',
  resendCode: 'إرسال رمز التحقق مرة أخرى',
  enterCode: 'يرجى إدخال رمز التحقق المكون من 4 أرقام',
  optional: 'اختياري',
  didNotCode: 'لم يتلق الرمز؟',
  textToRefer: 'أخبر أصدقائك وكسب',
  off: 'خصم',
  referralCode: 'رمز الإحالة',
  announcements: 'الإعلانات',
  referYour: 'أوصي صديق واكسب',
  shareCode: 'شارك رمز الإحالة مع أصدقائك واحصل على',
  referrral: 'رمز الإحالة',
  shareVia: 'شارك رمز الإحالة عبر',
  announcementDetails: 'تفاصيل الإعلانات',
  notifications: 'إشعارات',
  clearAll: 'مسح الكل',
  points: ' نقاط',
  events: 'الأحداث',
  noPackages: 'لا حزم',

  //Change Password
  changePassword: 'تغير كلمة المرور',
  oldPassword: 'كلمة المرور الحالية',
  newPassword: 'كلمة المرور الجديدة',
  confirmPassword: 'تأكيد كلمة المرور',
  enterTheOldPassword: 'ادخل كلمة المرور الحالية',
  enterTheNewPassword: 'ادخل كلمة المرور الجديدة',
  enterTheConfirmPassword: 'ادخل تأكيد كلمة المرور',

  //Trainer My Members
  myMembers: 'الأعضاء',
  memberDetails: 'تفاصيل الأعضاء',
  admissionDate: 'تاريخ التسجيل',
  myGoal: 'هدفي',
  exercisingPerWeek: 'عدد التمرين في الإسبوع',
  level: 'المستوى',
  phone: 'رقم النقال',
  personalIds: 'الرقم الشخصي',
  edit: 'تعديل',
  date: 'التاريخ',
  id: 'الرقم',
  updateWorkout: 'تحديث التمارين',
  updateDiet: 'تحديث النظام الغذائي',
  assignWorkout: 'تخصيص التمارين',
  addDiet: 'إضافة نظام غذائي',
  members: 'الأعضاء',
  startOn: 'يبدأ في',
  extendedTo: 'مُدد إلى',

  //Member Attendance
  myAttendance: 'سجل حضوري',
  attendance: 'سجل الحضور',
  checkIn: 'الدخول',
  checkOut: 'الخروج',
  totalHrs: 'عدد الساعات',
  weekly: 'إسبوعي',
  monthly: 'شهري',

  //notifications
  notify: `سنقوم بإعلامك عند وصول أي شيء`,
  noNotify: 'لا إشعارات حتى الان',
  notifications: 'إشعارات',
  allNotifications: 'جميع الإشعارات',
  ago: 'منذ',
  freeze: 'تجمد',

  //System Admin Panel
  dashboard: 'لوحة المعلومات',
  totalMembers: 'مجموع الأعضاء',
  newMembers: 'الأعضاء الجُدد',
  activeMembers: 'الأعضاء النشطون',
  pendingMembers: 'غير نشطين',
  branchSales: 'مبيعات الفروع',
  revenueDetails: 'تفاصيل الإيرادات',
  memberAttendance: 'حضور الأعضاء',
  mostSellingProducts: 'المُنتجات الأكثر مبيعاً',
  productName: 'إسم المنتج',
  location: 'الفرع',
  price: 'السعر',
  viewReport: 'عرض التقرير',
  all: 'الكل',
  totalSales: 'إجمالي المبيعات',
  present: 'حاضر',
  absent: 'غائب',
  salesIn: 'عملة البيع',

  //Book Appointment
  bookAppointment: "حجز المواعيد",
  bookAppointmentHistory: "جدول المواعيد",
  selectBranch: "إختر الفرع",
  trafficOverview: "نسبة تواجد الأعضاء",
  popularTimes: "الأيام",
  selectDateAndTime: "إختر التاريخ و الوقت",
  fromTime: "الوقت من",
  toTime: "الوقت إلى",
  selectTrainer: "إختر المُدرب",
  availableTimings: "المواعيد المتاحة",
  trainer: "المُدرب",
  status: 'الحالة',
  usuallyNotBusy: 'عادة غير مشغول',
  usuallyNotTooBusy: 'عادة ليس مشغول جداً',
  usuallyALittleBusy: 'عادة مشغول قليلاً',
  usuallyAboutToBeBusy: 'عادة على وشك أن يكون مشغولاً',
  usuallyBusy: 'عادة مشغول',
  Level: "المستوى",
  ExercisingPerWeek: "ممارسة الرياضة في الأسبوع",
  MyGoal: "هدفي",
  allTheFieldsAreRequired: 'كل المجالات مطلوبة',
  someFieldsAreIncorrect: 'بعض الحقول غير صحيحة'

}