export const en = {
    //weekDays
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sunday: "Sunday",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",

    //monthFullNames
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    Jan: 'Jan',
    Feb: 'Feb',
    Mar: 'Mar',
    Apr: 'Apr',
    May: 'May',
    Jun: 'Jun',
    Jul: 'Jul',
    Aug: 'Aug',
    Sep: 'Sep',
    Oct: 'Oct',
    Nov: 'Nov',
    Dec: 'Dec',
    pleaseSelect: 'Please Select',

    //Package Home 
    packages: 'Packages',
    alreadyRegistered: 'You have already registered for a package, If you want to request or purchase a new package then complete your face authentication in gym. !',

    //Package Details
    oneMonth: '1 Month',
    twoMonth: '2 Month',
    threeMonth: '3 Month',
    yes: 'Yes',
    no: 'No',
    packageDetails: 'Package Details',
    description: 'Description',
    doYouWantTrainer: 'Do You Want Trainer ?',
    period: 'Period',
    next: 'Next',
    pleaseSelectTrainer: 'Please select a trainer and period',
    pleaseSelectRequiredField: 'Please select required field',
    yourCurrentPlanSubscriptionIsActiveThrough: 'Your current plan subscription is active through',
    youCantBuyTheSamePackageTwice: `You can't buy the same package twice !`,

    //Trainer Question One
    beginner: 'Beginner',
    intermidiate: 'Intermediate',
    advanced: 'Advanced',
    whatIsYourLevel: `What's your level ?`,
    selectYourFitnessLevel: 'Select your fitness level',
    pleaseSelectOneOption: 'Please select one option',

    //Trainer Question Two
    oneDayAWeek: '1 Day a week',
    twoDayAWeek: '2 Day a week',
    threeDayAWeek: '3 Day a week',
    fourDayAWeek: '4 Day a week',
    fiveDayAWeek: '5 Day a week',
    sixDayAWeek: '6 Day a week',
    sevenDayAWeek: '7 Day a week',
    howManyDays: `How many day's you are planning to exercise per week ?`,

    //Trainer Question Three
    lossWeight: 'Loss Weight',
    gainWeight: 'Gain Weight',
    whatIsYourGoal: 'What is your goal ?',

    //Payment Question
    payOnline: 'Pay Online',
    payAtGym: 'Pay at Gym',
    submit: 'Submit',
    makePayment: 'Make Payment',
    paymentMethod: 'Payment Method',
    totalAmount: 'Total Amount',
    trainerFees: 'Trainer Fees',
    VAT: 'VAT',
    congratulations: 'Congratulations !!!',
    successfullyRequest: 'You have successfully requested a package for yourself !',
    successfullyRequestFingerPrint: 'You have successfully requested a package for yourself, now proceed to gym for furthere process !',

    //Renew packages
    currentPackages: 'Current Packages',
    active: 'Active',
    newPackages: 'New Packages',
    renew: 'Renew',
    alert: 'Alert',
    currentPlan: 'Current Plan',
    previousPlan: 'Previos Plan',
    inActive: 'In-Active',
    queued: 'Upcoming',
    futurePlan: 'Future Plan',
    yourPreviousPlanSubscriptionWasActiveThrough: 'Your previous plan subscription was active through',
    yourFuturePlanSubscriptionWillStartFrom: 'Your Future Plan Subscription will start from',

    //HomePage 
    myWorkouts: 'My Workouts',
    mySchedule: 'My Schedule',
    myTrainers: 'My Trainers',
    gymShop: 'GYM Shop',
    myDietPlan: 'My Diet Plan',
    myPackages: 'My Packages',
    startPackage: 'Start Package',
    offers: 'Offers',
    days: 'Days',
    daysLeft: 'Days Left',
    expiryOn: 'Expiry On',
    expiredOn: 'Expired On',
    firstPay: 'Pay for the package first',
    memberId: 'Member ID',
    mobile: 'Mobile',

    //Workouts 
    workouts: 'Workouts',
    workoutsAndCardios: 'Workouts & Cardios',
    sets: 'SETS',
    reps: 'REPS',
    kg: 'KG',
    time: 'TIME',
    km: 'KM',
    startWorkout: 'Start Workout',
    noData: 'Sorry ! No data available',
    instructions: 'Instructions',

    //Schedules
    schedule: 'Schedule',
    classes: 'Classes',


    //Diet
    diets: 'Diets',
    dietPlan: 'Diet Plan',
    calories: 'Calories',

    //Trainer
    myTrainer: 'My Trainer',
    trainerDetails: 'Trainer Details',

    //BMI 
    result: 'Result',
    underWeight: 'Underweight',
    normal: 'Normal',
    overWeight: 'Overweight',
    obese: 'Obese',
    severelyObese: 'Severely Obese',
    verySeverelyObese: 'Very Severely Obese',
    gender: 'Gender',
    age: 'Age',
    calculate: 'Calculate',
    weightProgress: 'Weight Progress',
    start: 'Start',
    current: 'Current',
    goal: 'Goal',
    today: 'Today',
    trackWeight: 'Track Weight',
    howMuchDoYouWeightToday: 'How much do you weight today ?',
    whatIsYourGoalWeight: 'What is your goal weight ?',
    updateWeight: 'Update Weight',

    //Menu items
    webShop: 'Web Shop',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    description: 'Description',
    yourCartIsEmpty: 'Your cart is empty !!',
    addItemsToItNow: 'Add items to it now',
    myCart: 'My Cart',
    subTotal: 'Sub Total',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    checkout: 'Checkout',
    payWithCreditCard: 'Pay with Credit Card',
    myOrders: 'My Orders',
    order: 'Order',
    dateAndTime: 'Date & Time',
    paymentMode: 'Payment Mode',
    invoice: 'Invoice',
    invoices: 'Invoices',
    orderDetails: 'Order Details',
    addedToCart: 'Added to Cart',
    QTY: 'QTY',
    amount: 'Amount',
    orderHistory: 'Order History',

    //Water Intake 
    pleaseSelectADateToContinue: 'Please Select a Date To Continue',
    drunk: 'Drunk',
    outOf: 'Out of',
    target: 'Target',
    addWater: 'Add Water',
    updateTarget: 'Update Target',
    dailyTarget: 'Daily Target',
    progress: 'Progress',
    trackingWaterProgress: 'Tracking Water Progress',
    reminder: 'Reminder',
    setAReminder: 'Set a Reminder',
    customize: 'Customize',
    enterWaterLevel: 'Enter Water Level',
    records: 'Records',
    enterTarget: 'Enter Water Target',
    setReminderToDrinkWater: 'Set Reminder to Drink Water',
    input: 'Input your information, customize your hydration plan',
    from: 'From',
    to: 'To',
    remindMeEvery: 'Remind me every',
    remindMe: 'Remind me',
    save: 'SAVE',
    setYourTimeIntervals: 'Set your time intervals',
    setNumberOfReminders: 'Set number of reminders',
    of: 'OF',
    enterWaterLevel: 'Enter Water Level',


    //Drawer Menu
    home: 'Home',
    myProfile: 'My Profile',
    myClasses: 'My Classes',
    qrCode: 'QRCode',
    myInvoices: 'My Invoices',
    contact: 'Contact',
    feedback: 'Feedback',
    aboutUs: 'About Us',
    exploreTheCentres: 'Explore the centres',
    referAFriend: 'Refer a friend',
    settings: 'Settings',
    logout: 'Logout',
    qr: 'QR',

    //Bottom Tab Navigator
    reward: 'My Rewards',
    BMI: 'BMI',
    waterIntake: 'Water Intake',

    //Trainer Waorkout 
    addWorkout: 'Add Workout',
    selectMember: 'Select Member',
    cardio: 'Cardio',
    assignWorkouts: 'Assign Workouts',
    activities: 'Activities',
    note: 'Note',
    workoutLevel: 'Workout Level',
    updateWorkout: 'Update Workout',
    weightTrainer: 'WEIGHT',
    distance: 'DISTANCE',
    missingFields: 'Some fields are missing',

    //Trainer Diet Plan
    dietPlanSessions: 'Diet Plan Sessions',
    assignDietPlans: 'Assign Diet Plans',
    foodItems: 'Food Items',
    QTYOrGrams: 'QTY/Grams',
    specOrAdvice: 'Specifications/Advices',
    dietPlans: 'Diet Plans',
    add: 'Add',
    search: 'Search',

    //settings
    languages: 'Languages',
    changePassword: 'Change Password',
    notifications: 'Notifications',

    //Trainer Home 
    empId: 'Emp ID',

    //Classes
    branch: 'Branch',
    remainingSeats: 'Remaining Seats',
    classDetails: 'Class Details',
    daysIncluded: 'Days Included',
    bookNow: 'Book Now',
    room: 'Room',

    //Feedbacks
    feedbacks: 'Feedbacks',
    suggestions: 'Suggestions',
    complaints: 'Complaints',
    feedbackDetails: 'Feedback Details',
    gymOwnerComments: 'Gym Management Comments',
    types: 'Types',

    //Contact us 
    contactUs: 'Contact Us',
    showRoute: 'Show Route',
    maps: 'Maps',
    estTime: 'Estimated Time',
    cancel: 'Cancel',
    sorry: 'Sorry! There are no routes found from your current location to the gym, please try with some other locations of our branch',

    //Reward 
    rewards: 'Rewards',
    giftCards: 'Gift Cards',
    history: 'History',
    points: 'Points',
    currentPoints: 'Current Points',
    end: 'End',
    redeem: 'Redeem',
    totalPoints: 'Total Points',
    giftCardDetails: 'Gift card details',
    rewardDetails: 'Reward Details',

    //Login and Sign up
    email: 'Email',
    password: 'Password',
    login: 'Login',
    forgotPassword: "Forgot Password",
    forgotPasswordSuccess: "An email with your password has been sent on your registered e-mail id !",
    dontHaveAnAccount: "Don't Have an Account ?",
    signUp: "SIGN UP",
    name: 'Name',
    personalId: 'Personal Id',
    dateOfBirth: 'Date of birth',
    age: 'Age',
    height: 'Height (in cm)',
    weight: 'Weight (in kg)',
    emergencyNumber: 'Emeregency Number',
    relationship: 'Relationship',
    nationality: 'Nationality',
    gender: 'Gender',
    branch: 'Branch',
    uploadPhoto: 'Upload Photo',
    takePicture: 'Take Picture',
    selectFromGallery: 'Select From Gallery',
    confirmPassword: 'Confirm Password',
    nameError: 'Name is empty',
    nameErrorTwo: 'Enter Name',
    emailError: 'Email is empty',
    emailErrorTwo: 'Email is not valid',
    emailErrorThree: 'Enter email',
    personalError: 'Personal id is empty',
    personalErrorTwo: 'Enter personal id',
    mobileError: 'Mobile number is empty',
    mobileErrorTwo: 'Enter Valid Contact',
    mobileErrorThree: 'Enter Contact',
    dobError: 'DOB is empty',
    dobErrorTwo: 'Age is less',
    nationalityError: 'Nationality is empty',
    genderError: 'Gender is empty',
    branchError: 'Branch is empty',
    imageError: 'Image is required',
    passwordError: 'Password is empty',
    confirmError: 'Confirm Password is empty',
    passwordErrorTwo: 'Password should be atleas 5 characters long',
    confirmErrorTwo: 'Confirm password field is empty',
    confirmErrorThree: 'Password did not match',
    emailVerification: 'Email Verification',
    verification: 'A verification code has been sent on your email, please verify your account by entering the verification code !',
    resendCode: 'RESEND CODE',
    enterCode: 'Enter 4 - Digit Code',
    optional: 'Optional',
    didNotCode: `Didn't receive the code ?`,
    textToRefer: 'Refer your friends and Earn',
    off: 'OFF',
    referralCode: 'Referral Code',
    announcements: 'Announcements',
    referYour: 'Refer your friend and Earn',
    shareCode: 'Share this referral code with your friends and get',
    referrral: 'Referral Code',
    shareVia: 'Share your referral code via',
    announcementDetails: 'Announcement Details',
    notifications: 'Notifications',
    clearAll: 'CLEAR All',
    points: 'points',
    events: 'Events',
    noPackages: 'No Packages',

    //ChangePassword
    changePassword: 'Change Password',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    enterTheOldPassword: 'Enter the Old Password',
    enterTheNewPassword: 'Enter the New Password',
    enterTheConfirmPassword: 'Enter the Confirm Password',


    //Trainer My Members
    myMembers: 'My Members',
    memberDetails: 'Member Details',
    admissionDate: 'Admission Date',
    myGoal: 'My Goal',
    exercisingPerWeek: 'Exercising Per Week',
    level: 'Level',
    phone: 'Phone',
    personalIds: 'Personal ID',
    edit: 'Edit',
    date: 'Date',
    id: 'ID',
    updateWorkout: 'Update Workout',
    updateDiet: 'Update Diet',
    assignWorkout: 'Assign Workout',
    addDiet: 'Add Diet',
    members: 'Members',
    startOn: 'Start On',
    extendedTo: 'Extended To',

    //Member Attendance
    myAttendance: 'My Attendance',
    attendance: 'Attendance',
    checkIn: 'Check-In',
    checkOut: 'Check-Out',
    totalHrs: 'Total Hrs',
    weekly: 'Weekly',
    monthly: 'Monthly',

    //notifications
    notify: `We'll notify you when there is something arrives`,
    noNotify: 'No Notifications Yet',
    notifications: 'Notifications',
    allNotifications: 'All Notifications',
    ago: 'ago',
    freeze: 'Freezed',

    //System Admin Panel
    dashboard: 'Dashboard',
    totalMembers: 'Total Members',
    newMembers: 'New Members',
    activeMembers: 'Active Members',
    pendingMembers: 'Pending Members',
    branchSales: 'Branch Sales',
    revenueDetails: 'Revenue Details',
    memberAttendance: 'Member Attendance',
    mostSellingProducts: 'Most Selling Products',
    productName: 'Product Name',
    location: 'Location',
    price: 'Price',
    viewReport: 'View Report',
    all: "All",
    totalSales: 'Total Sales',
    present: 'Present',
    absent: 'Absent',
    salesIn: 'Sales In',
    type: 'Type',
    pointOfSales: 'Point Of Sales',
    salesByBranch: 'Sales By Branches',
    reports: 'Reports',
    generalSales: 'General Sales',
    generateReport: 'Generate Report',
    salesByTransactionType: 'Sales by Transaction Type',
    salesByBranch: 'Sales by Branch',
    sno: 'S.No.',
    receiptNo: 'Receipt No.',
    memberName: 'Member Name',
    mobileNo: 'Mobile No.',
    transactionType: 'Transaction Type',
    paidAmount: 'Paid Amount',
    cash: 'Cash',
    card: 'Card',
    digital: 'Digital',
    cheque: 'Cheque',
    doneBy: 'Done by',
    grandTotal: 'Grand Total',
    //Book Appointment
    bookAppointment: "Book Appointment",
    bookAppointmentHistory: "Appointment History",
    selectBranch: "Select Branch",
    trafficOverview: "Traffic Overview",
    popularTimes: "Popular Times",
    selectDateAndTime: "Select Date & Time",
    fromTime: "From Time",
    toTime: "To Time",
    selectTrainer: "Select Trainer",
    availableTimings: "Available Timings",
    trainer: "Trainer",
    status: 'Status',
    usuallyNotBusy: 'Usually not busy',
    usuallyNotTooBusy: 'Usually not too busy',
    usuallyALittleBusy: 'Usually a little busy',
    usuallyAboutToBeBusy: 'Usually about to be busy',
    usuallyBusy: 'Usually busy',
    Level: "Level",
    ExercisingPerWeek: "Exercising per week",
    MyGoal: "My Goal",
    allTheFieldsAreRequired: 'All the fields are required',
    someFieldsAreIncorrect: 'Some fields are incorrect',

    //Book A Trainer
    selectPackage: 'Select Package',
    selectPeriod: 'Select Period',
    startDate: 'Start Date',
    endDate: 'End Date',
    bookTrainer: 'Book A Trainer',

    //Invoice
    paymentDetails: 'Payment Details',
    packageName: 'Package Name',
    totalAmount: 'Total Amount',
    toBePaid: 'To Be Paid',
    paidAmount: 'Paid Amount',
    remainingAmount: 'Remaining Amount',
    installmentHistory: 'Installment History',
    installmentType: 'Installment Type',
    amount: 'Amount',
    dueDate: 'Due Date',
    paidDate: 'Paid Date',
    status: 'Status',
    action: 'Action',
    trainerName: 'Trainer Name',
    receipt: 'Receipt',
    taxInvoice: 'Tax Invoice',
    vatRegNumber: 'VAT Reg Number',
    taxInvoiceNumber: 'Tax Invoice No',
    receiptTotal: 'Receipt Total',
    address: 'Address',
    telephone: 'Telephone',
    id: 'ID',
    mob: 'Mob',
    name: 'Name',
    amountTotal: 'Amount Total',
    vat: 'VAT',
    digital: 'Digital',
    cheque: 'Cheque',
    chequeDate: 'Cheque Date',
    card: 'Card',
    cash: 'Cash',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    paidAmount: 'Paid Amount',
    membershipCannotBeRefundedOrTransferredToOthers: 'Membership cannot be refunded or transferred to others',
    thankYou: 'Thank You',
    followUs: 'Follow Us',
    pleaseClass: "Please book this class from the gym as this class is paid!",
    youHaveSuccesfullyRequestedATrainer: "You have successfully requested a trainer for yourself !",
    youAreNotAllowedToSelectTrainer: "You are not allowed to select this date as the trainer expiry date is greater than your package expiry date.",
    eitherTrainer: "Either this member trainer is not expired or the package is expired. Please check in my trainers tab !",
    packageSuccesfully: "You have successfully requested a package for yourself !",
    packageSuccessfullyProceed: "You have successfully requested a package for yourself, now proceed to gym for payment process !",
    congrats: "Congratulations !!",
    servedBy: 'Served By',
    verify: 'Verify'

}